spring:
  application:
    name: bompastor-api
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:mydb
    driverClassName: org.h2.Driver
    sql:
      init:
        mode: always
    h2:
      console.enabled: true
  jpa:
    defer-datasource-initialization: true
    show-sql: true